export const ADDTOORDERBOOK = 'ADDTOORDERBOOK';
export const DELETEORDERBOOK = 'DELETEORDERBOOK';
export const INCREMENTCOUNTBOOK = 'INCREMENTCOUNTBOOK';
export const DECREMENTCOUNTBOOK = 'DECREMENTCOUNTBOOK';
export const ESCAPEBOOKS = 'ESCAPEBOOKS';